# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: 'Lacework Inline Scanner'
- name: image_repo
- name: image_tag

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    docker build -t $(IMAGE_REPO):$(IMAGE_TAG) .
  displayName: 'Build the Docker Image'

- script: |
    docker run --rm -e LW_ACCOUNT_NAME -e LW_ACCESS_TOKEN -v /var/run/docker.sock:/var/run/docker.sock \
    lacework/lacework-inline-scanner:latest image evaluate $(IMAGE_REPO) $(IMAGE_TAG)
  displayName: 'Perform Lacework Image Assurance Scan'
  env:
    LW_ACCESS_TOKEN: $(LW_ACCESS_TOKEN)
    LW_ACCOUNT_NAME: $(LW_ACCOUNT_NAME)
