name: Docker Build/Scan/Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 4"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Scan-Push:
    runs-on: ubuntu-latest
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
      LW_SCANNER_SAVE_RESULTS: true
      LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
      IMAGE_REPO: alannix/nix-foundation
      IMAGE_TAG: latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the latest Docker image
        run: docker build -t ${IMAGE_REPO}:${IMAGE_TAG} .

      - name: Download Lacework Scanner
        run: |
          curl -LJO https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64
          sudo mv lw-scanner-linux-amd64 lw-scanner
          sudo chmod +x lw-scanner

      - name: Lacework Image Assurance Scan
        run: |
          ./lw-scanner image evaluate ${IMAGE_REPO} ${IMAGE_TAG} \
            --build-id ${{ github.run_id }} --html --html-file lacework-report.html
            --policy --fail-on-violation-exit-code 1

      - name: Save Lacework HTML Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lacework-report
          path: lacework-report.html

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push the latest Docker image
        run: docker push ${IMAGE_REPO}:${IMAGE_TAG}
